export const Tabledata = [
  {
    id: 1,
    rank: 12,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 3,
    rank: 2,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "-0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "+11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 3,
    rank: 13,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "-0.9%",
    day: "-6.2%",
    week: "+6.9%",
    month: "+11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 4,
    rank: 14,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 5,
    rank: 15,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 6,
    rank: 16,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
    ],
  },
  {
    id: 7,
    rank: 17,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 8,
    rank: 18,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "-0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "+74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 9,
    rank: 19,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 10,
    rank: 100,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "+74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 11,
    rank: 111,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 12,
    rank: 112,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "+11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 13,
    rank: 113,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "+11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [{ link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" }],
  },
  {
    id: 14,
    rank: 114,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "-6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "+74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 15,
    rank: 115,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 16,
    rank: 116,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 17,
    rank: 117,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "-0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "+11.1%",
    year: "+74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 18,
    rank: 118,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 19,
    rank: 119,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },

  {
    id: 20,
    rank: 120,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 21,
    rank: 121,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "-6.2%",
    week: "-6.9%",
    month: "+11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 22,
    rank: 122,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 23,
    rank: 123,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 24,
    rank: 124,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "-0.9%",
    day: "-6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 25,
    rank: 125,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "+6.9%",
    month: "+11.1%",
    year: "+74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://www.gate.io/trade/ATA_USDT?ref=UFEQVV1c", name: "Gate.io", price: "$0.04726", icon: "reg5.png" },
      { link: "https://www.bitmart.com/trade?symbol=ATA_USDT&r=cjMWSr", name: "BitMart", price: "$0.04740", icon: "reg6.png" },
      { link: "https://www.mexc.com/exchange/TPT_USDT?inviteCode=mexc-1WaJ1", name: "MEXC", price: "$0.007937", icon: "reg2.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
  {
    id: 26,
    rank: 126,
    icon: "/automata-icon.png",
    name: "Automata",
    price: "$0.04699",
    marketCap: "$27.62M	",
    volume: "$4.21M",
    hour: "+0.9%",
    day: "+6.2%",
    week: "-6.9%",
    month: "-11.1%",
    year: "-74.4%",
    links: [
      { links: "https://coinmarketcap.com/currencies/automata-network", icon: "/market-cap.jpg" },
      { links: "https://www.coingecko.com/coins/automata", icon: "/coingico.png" },
      { links: "https://www.tradingview.com/chart/?symbol=BINANCE:ATAUSDT&aff_id=143493", icon: "/tradingview.png" },
    ],
    tradeList: [
      { link: "https://www.binance.com/trade/ATA_USDT?layout=pro&ref=BRM28YZ5&type=spot", name: "Binance", price: "$0.04720", icon: "reg1.png" },
      { link: "https://www.kucoin.com/trade/ATA-USDT?rcode=P8Neuc", name: "Kucoin", price: "$0.04702", icon: "reg4.png" },
      { link: "https://bingx.com/spot/FORTHUSDT/?ref=RFLWBK", name: "Bybit", price: "$2.420", icon: "reg3.png" },
    ],
  },
];
